### PR TITLE
added logic for selecting addresses to be pulled from closeio, also p…

### PR DESCRIPTION
**Pull request by timliuhull**
@unity 
@michaloo 

Added unit tests, but was unable to test dropdown in dashboard because I have no api key...

### CODE REVIEW

**Comment by unity** [comment]
is this deployed in Staging for review ?

**Comment by timliuhull** [comment]
Does the develop branch get deployed to staging automatically?

Also, I was able to test the address dropdown, seems to work fine and imported new data with addresses of multiple types

**Comment by unity** [comment]
It does - if you could QA it and it’s working then LGTM

**Comment by timliuhull** [comment]
We have qa'd the fix and the customer says it looks good

**Pull request merged**
